"""Render a team's `build:` spec into a Docker build hook (C24).

A team that declares `build:` in agent.yaml needs its host tools baked into the
container image. Rather than `FROM modastack-base` + tool layers on top — which
re-runs every team's apt/npm/run on each framework release (the FROM digest
moves) — we render the spec to a single shell script (`team-deps.sh`) and the
ONE Dockerfile runs it as a stable layer BELOW the volatile framework-wheel copy
(via the `TEAM_DEPS` build-arg hook). A code-only framework release then rebuilds
only the wheel layer; the team's tools stay cached. See
docs/design/CUSTOM_AGENT_DEPS.md §"three clocks" / §layering.

The script:
  * `apt` / `npm` install system-wide as **root** (npm globals land in
    /usr/local/bin — on PATH, not under HOME, so no seeding needed).
  * `run` steps execute as the **modastack** user with HOME pointed at a
    dedicated seed dir (/opt/modastack/home-seed). `env HOME=…` makes `~`
    expand to the seed (an inline `HOME=… cmd ~/x` would NOT — tilde expands
    before the assignment). The entrypoint copies the seed onto the volume HOME
    at boot, so ~-relative tools (e.g. gstack's skills) survive the volume
    remap that points runtime ~ at /data/home.
  * a content stamp lets the entrypoint re-seed only when the tools change.
  * `verify: requires` re-runs the team's requires[].check as the final step,
    so a missing tool fails the BUILD (CI), not production dispatch.
"""

from __future__ import annotations

import hashlib
import json
import shlex
from pathlib import Path

from modastack.config import BuildSpec, Config

# Must match docker-entrypoint.sh's seed source and the stamp filename.
SEED_HOME = "/opt/modastack/home-seed"
TOOL_STAMP = ".modastack-tool-stamp"
APP_USER = "modastack"


def team_deps_hash(spec: BuildSpec) -> str:
    """Stable short hash of the build inputs — the seed stamp + image cache key.

    Keyed on what actually changes the baked tools (apt/npm/run/verify/base), so
    an unrelated agent.yaml edit doesn't churn the stamp.
    """
    payload = json.dumps(
        {
            "base": spec.base,
            "apt": spec.apt,
            "npm": spec.npm,
            "run_root": spec.run_root,
            "run": spec.run,
            "verify": spec.verify_requires,
        },
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


def render_team_deps_script(cfg: Config) -> str:
    """Render the `build:` spec to the team-deps.sh hook script.

    Raises ValueError if the team has no declarative build (None, or a pure
    raw-Dockerfile escape hatch — that path bypasses this renderer).
    """
    spec = cfg.build
    if spec is None:
        raise ValueError("team has no build: spec to render")
    declarative = bool(spec.apt or spec.npm or spec.run_root or spec.run
                       or spec.verify_requires)
    if spec.dockerfile and not declarative:
        raise ValueError(
            "team uses a raw Dockerfile escape hatch; build it directly, "
            "do not render"
        )
    if not declarative:
        raise ValueError("team has no declarative build: spec to render")

    seeds = bool(spec.run)
    needs_seed_dir = seeds or spec.verify_requires
    stamp = team_deps_hash(spec)

    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# GENERATED by modastack.build_render — do not edit.",
        "# Runs as root, BELOW the framework-wheel layer (C24 team-deps hook).",
        "set -euo pipefail",
        "",
    ]

    if spec.apt:
        pkgs = " ".join(shlex.quote(p) for p in spec.apt)
        lines += [
            "echo '== apt =='",
            "apt-get update",
            f"apt-get install -y --no-install-recommends {pkgs}",
            "rm -rf /var/lib/apt/lists/*",
            "",
        ]

    if spec.npm:
        pkgs = " ".join(shlex.quote(p) for p in spec.npm)
        lines += ["echo '== npm =='", f"npm install -g {pkgs}", ""]

    for step in spec.run_root:
        lines += [
            f"echo {shlex.quote('== run_root: ' + step[:60] + ' ==')}",
            step,  # already root; run as-is
            "",
        ]

    if needs_seed_dir:
        lines += [
            f"install -d -o {APP_USER} -g {APP_USER} {SEED_HOME}",
            "",
        ]

    for step in spec.run:
        lines += [
            f"echo {shlex.quote('== run: ' + step[:60] + ' ==')}",
            f"gosu {APP_USER} env HOME={SEED_HOME} bash -lc {shlex.quote(step)}",
            "",
        ]

    if seeds:
        # Stamp lives in the seed; the entrypoint compares it to the volume's
        # copy and re-seeds on a mismatch (a deps bump → new hash → re-seed).
        lines += [
            f"echo {shlex.quote(stamp)} > {SEED_HOME}/{TOOL_STAMP}",
            f"chown {APP_USER}:{APP_USER} {SEED_HOME}/{TOOL_STAMP}",
            "",
        ]

    if spec.verify_requires and cfg.requires:
        lines.append("echo '== verify requires =='")
        for entry in cfg.requires:
            lines += [
                f"echo {shlex.quote('verify ' + entry.name)}",
                f"gosu {APP_USER} env HOME={SEED_HOME} bash -lc {shlex.quote(entry.check)}",
            ]
        lines.append("")

    lines.append("echo '== team-deps complete =='")
    return "\n".join(lines) + "\n"


def load_team_config(team_dir: Path) -> Config:
    """Load a team's Config straight from <team_dir>/agent.yaml (source layout).

    Config.load() expects an installed project (.modastack/agent.yaml); a team
    SOURCE dir holds agent.yaml at its root, so parse it directly.
    """
    agent_yaml = team_dir / "agent.yaml"
    if not agent_yaml.exists():
        raise FileNotFoundError(f"no agent.yaml in {team_dir}")
    return Config._parse(agent_yaml)


def _main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(
        description="Render a team's build: spec to a Docker team-deps hook."
    )
    ap.add_argument("team_dir", type=Path, help="team source dir (holds agent.yaml)")
    ap.add_argument("--out", type=Path, help="write script here (default: stdout)")
    ap.add_argument(
        "--print-hash",
        action="store_true",
        help="print the deps hash instead of the script (image tag / cache key)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 0 if the team declares a build, 2 otherwise (no output)",
    )
    args = ap.parse_args(argv)

    cfg = load_team_config(args.team_dir)
    if args.check:
        return 0 if cfg.build is not None else 2
    if cfg.build is None:
        ap.error(f"{args.team_dir} declares no build: spec")

    if args.print_hash:
        print(team_deps_hash(cfg.build))
        return 0

    script = render_team_deps_script(cfg)
    if args.out:
        args.out.write_text(script)
        args.out.chmod(0o755)
    else:
        print(script, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
