"""Render a team's `build:` spec into a Docker build hook (C24).

A team that declares `build:` in agent.yaml needs its host tools baked into the
container image. Rather than `FROM modastack-base` + tool layers on top — which
re-runs every team's apt/npm/run on each framework release (the FROM digest
moves) — we render the spec to a single shell script (`team-deps.sh`) and the
ONE Dockerfile runs it as a stable layer BELOW the volatile framework-wheel copy
(via the `TEAM_DEPS` build-arg hook). A code-only framework release then rebuilds
only the wheel layer; the team's tools stay cached. See
docs/design/CUSTOM_AGENT_DEPS.md §"three clocks" / §layering.

The script:
  * `apt` / `npm` install system-wide as **root** (npm globals land in
    /usr/local/bin — on PATH, not under HOME).
  * `run` steps execute as the **modastack** user with HOME pinned to the
    user's real image home (/home/modastack) — the SAME path the agent runs
    with at runtime, so ~-relative tools (e.g. gstack's ~/dev/gstack) are baked
    in place and read directly at runtime; nothing is copied onto the volume.
    `env HOME=…` makes `~` expand to the home (an inline `HOME=… cmd ~/x` would
    NOT — tilde expands before the assignment). `env -u CLAUDE_CONFIG_DIR` is
    critical: the runtime sets CLAUDE_CONFIG_DIR to the volume, but at BUILD
    time tools must write to the IMAGE — so we strip it here.
  * personal skills are baked at BAKED_SKILLS (/opt/modastack/skills), OUTSIDE
    ~/.claude, via a build-time `~/.claude/skills -> BAKED_SKILLS` symlink. This
    frees ~/.claude so the entrypoint can point the whole dir at the durable
    volume config dir — making `~/.claude/{projects,settings.json,skills,…}` all
    resolve to Claude's real state at runtime (docker-entrypoint.sh §2b), so any
    skill keyed off ~/.claude or $HOME just works.
  * `verify: requires` re-runs the team's requires[].check as the final step,
    against the SAME image HOME the runtime uses — so the build's verify and
    production's dispatch gate read identical paths, closing the
    build-time-vs-runtime HOME gap that the old seed-copy model left open.
"""

from __future__ import annotations

import hashlib
import json
import shlex
from pathlib import Path

from modastack.config import BuildSpec, Config

# The modastack user's real image home — where `run` steps bake ~-relative tools
# and where the agent runs at runtime (docker-entrypoint.sh keeps HOME here and
# redirects only Claude's durable state off to the volume via CLAUDE_CONFIG_DIR).
TEAM_HOME = "/home/modastack"
# Personal skills bake HERE — an image path OUTSIDE ~/.claude — so the entrypoint
# can point ~/.claude at the durable volume config dir without clobbering them.
# A build-time `~/.claude/skills -> BAKED_SKILLS` symlink lets tools that write
# to ~/.claude/skills (gstack) land here transparently. See docker-entrypoint.sh.
BAKED_SKILLS = "/opt/modastack/skills"
APP_USER = "modastack"


def team_deps_hash(spec: BuildSpec) -> str:
    """Stable short hash of the build inputs — the team-image cache key / tag.

    Keyed on what actually changes the baked tools (apt/npm/run/verify/base), so
    an unrelated agent.yaml edit doesn't churn the image tag.
    """
    payload = json.dumps(
        {
            "base": spec.base,
            "apt": spec.apt,
            "npm": spec.npm,
            "run_root": spec.run_root,
            "run": spec.run,
            "verify": spec.verify_requires,
        },
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


def render_team_deps_script(cfg: Config) -> str:
    """Render the `build:` spec to the team-deps.sh hook script.

    Raises ValueError if the team has no declarative build (None, or a pure
    raw-Dockerfile escape hatch — that path bypasses this renderer).
    """
    spec = cfg.build
    if spec is None:
        raise ValueError("team has no build: spec to render")
    declarative = bool(spec.apt or spec.npm or spec.run_root or spec.run
                       or spec.verify_requires)
    if spec.dockerfile and not declarative:
        raise ValueError(
            "team uses a raw Dockerfile escape hatch; build it directly, "
            "do not render"
        )
    if not declarative:
        raise ValueError("team has no declarative build: spec to render")

    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# GENERATED by modastack.build_render — do not edit.",
        "# Runs as root, BELOW the framework-wheel layer (C24 team-deps hook).",
        "set -euo pipefail",
        "",
    ]

    if spec.apt:
        pkgs = " ".join(shlex.quote(p) for p in spec.apt)
        lines += [
            "echo '== apt =='",
            "apt-get update",
            f"apt-get install -y --no-install-recommends {pkgs}",
            "rm -rf /var/lib/apt/lists/*",
            "",
        ]

    if spec.npm:
        pkgs = " ".join(shlex.quote(p) for p in spec.npm)
        lines += ["echo '== npm =='", f"npm install -g {pkgs}", ""]

    for step in spec.run_root:
        lines += [
            f"echo {shlex.quote('== run_root: ' + step[:60] + ' ==')}",
            step,  # already root; run as-is
            "",
        ]

    # `run` and `verify` steps drop to the modastack user with HOME pinned to the
    # image home and CLAUDE_CONFIG_DIR stripped, so ~-relative tools bake into the
    # image (read directly at runtime — no seed copy). `-u CLAUDE_CONFIG_DIR`
    # defends against the runtime ENV leaking into the build and redirecting
    # writes to the (build-time-absent) volume.
    as_user = f"gosu {APP_USER} env -u CLAUDE_CONFIG_DIR HOME={TEAM_HOME} bash -lc"

    if spec.run:
        # Bake personal skills OUTSIDE ~/.claude (at BAKED_SKILLS) via a build-time
        # symlink, so a tool writing ~/.claude/skills/X lands in the immutable
        # image path — leaving ~/.claude itself free for the entrypoint to point
        # at the durable volume config dir (full ~/.claude coincidence at runtime).
        lines += [
            "echo '== bake skills into image path =='",
            f"install -d -o {APP_USER} -g {APP_USER} {BAKED_SKILLS}",
            f"{as_user} {shlex.quote(f'mkdir -p ~/.claude && rm -rf ~/.claude/skills && ln -sfn {BAKED_SKILLS} ~/.claude/skills')}",
            "",
        ]

    for step in spec.run:
        lines += [
            f"echo {shlex.quote('== run: ' + step[:60] + ' ==')}",
            f"{as_user} {shlex.quote(step)}",
            "",
        ]

    if spec.verify_requires and cfg.requires:
        lines.append("echo '== verify requires =='")
        for entry in cfg.requires:
            lines += [
                f"echo {shlex.quote('verify ' + entry.name)}",
                f"{as_user} {shlex.quote(entry.check)}",
            ]
        lines.append("")

    lines.append("echo '== team-deps complete =='")
    return "\n".join(lines) + "\n"


def load_team_config(team_dir: Path) -> Config:
    """Load a team's Config straight from <team_dir>/agent.yaml (source layout).

    Config.load() expects an installed project (.modastack/agent.yaml); a team
    SOURCE dir holds agent.yaml at its root, so parse it directly.
    """
    agent_yaml = team_dir / "agent.yaml"
    if not agent_yaml.exists():
        raise FileNotFoundError(f"no agent.yaml in {team_dir}")
    return Config._parse(agent_yaml)


def _main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(
        description="Render a team's build: spec to a Docker team-deps hook."
    )
    ap.add_argument("team_dir", type=Path, help="team source dir (holds agent.yaml)")
    ap.add_argument("--out", type=Path, help="write script here (default: stdout)")
    ap.add_argument(
        "--print-hash",
        action="store_true",
        help="print the deps hash instead of the script (image tag / cache key)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 0 if the team declares a build, 2 otherwise (no output)",
    )
    args = ap.parse_args(argv)

    cfg = load_team_config(args.team_dir)
    if args.check:
        return 0 if cfg.build is not None else 2
    if cfg.build is None:
        ap.error(f"{args.team_dir} declares no build: spec")

    if args.print_hash:
        print(team_deps_hash(cfg.build))
        return 0

    script = render_team_deps_script(cfg)
    if args.out:
        args.out.write_text(script)
        args.out.chmod(0o755)
    else:
        print(script, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
