"""Scaffold bring-your-own-repo CI deploy automation (`bobi deploy-init`).

Turns DEPLOYMENT.md §7.2 B into one command: emit a standalone
`deploy-agent-teams.yml` + a `deployments/` skeleton, then print the exact
`fly`/`gh` commands to wire the secrets — derived from each team's *declared*
`${VAR}` set, so the list is always right.

The generated workflow is the **standalone** fleet-repo form of
`.github/workflows/deploy-agent-teams.yml.example`: it installs `bobi` from
PyPI (the engine's binary mode ships the deploy assets, so a team repo needs no
framework checkout), and its orphans job enumerates the fleet inline instead of
calling `scripts/fleet.sh`. The version is pinned at scaffold time to the bobi
that generated it.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

# Workflow template. `__BOBI_VERSION__` is substituted at scaffold time. We
# use a sentinel token (not str.format / f-string) so the file's `${{ … }}`
# GitHub expressions and `${…}` shell vars survive verbatim. Keep this in sync
# with .github/workflows/deploy-agent-teams.yml.example and the fleet-repo
# deployment model.
WORKFLOW_TEMPLATE = r'''name: Deploy agent teams

# Reconcile deployments/<name>.yaml to live Fly instances. Standalone
# ("bring-your-own-repo") deploy pipeline: this repo holds agent teams + their
# deployment config and consumes the published `bobi` framework from PyPI
# (no framework checkout). Generated by `bobi deploy-init`. Two deltas vs the
# framework's own copy:
#   * the deploy job installs `bobi==<pin>` from PyPI instead of `pip
#     install -e .` — the engine's binary mode (bundled bobi/_deploy assets)
#     makes a checkout unnecessary.
#   * the orphans job enumerates the fleet inline via `fly apps list` + the
#     BOBI_FLEET stamp, instead of the framework's scripts/fleet.sh (which
#     isn't present here).
#
# WHEN it runs:
#   push of a `deploy-*` tag -> reconcile the active set (provision new, update
#                           existing). Tag pushes run from the TAGGED commit.
#   workflow_dispatch    -> manual; optional `only:` to scope to one deployment.
#
# This workflow is a THIN CLIENT: all deployment business logic lives in the
# `bobi deploy` primitive (idempotent provision-or-update, delivery-mode
# selection, secret validation, the Fly mechanics). The Action only orchestrates.
#
#   active deployment   = deployments/<name>.yaml (defaults.yaml excluded).
#   inactive            = anything else (e.g. <name>.yaml.example) — never deployed.
#   removed deployment  -> nothing automatic; the orphans job surfaces the
#                          now-unmanaged Fly app for a human `bobi destroy`.
#
# Required configuration (see the `bobi deploy-init` output):
#   secrets.FLY_API_TOKEN   Fly deploy token (org-scoped: `fly tokens create org`).
#                           Absent -> the workflow no-ops, so committing
#                           deployments/ before wiring the fleet never breaks CI.
#   Environment "<tenant>" per TENANT, holding that tenant's per-key secrets keyed
#   `<TEAM>__<KEY>` — e.g. ENG_TEAM__SLACK_BOT_TOKEN. The deploy job filters them
#   from toJSON(secrets) by the <TEAM>__ prefix into an --env-file; the engine
#   reconciles to the team's declared agent.yaml set and prunes the rest.
#   NOTE: the <tenant> prefix is organization, not isolation — toJSON(secrets) in
#   any cell sees every secret in scope. Real isolation needs an Environment (or
#   repo) per tenant with no shared secrets across them.

env:
  # The published framework version this repo's instances are built on. Bump to
  # adopt a new bobi release (rebuilds team images on the next deploy).
  BOBI_VERSION: "__BOBI_VERSION__"

on:
  push:
    tags:
      - "deploy-*"
  workflow_dispatch:
    inputs:
      only:
        description: "Reconcile only this deployment name (default: all active)"
        required: false

# Serialize fleet reconciliation so two pushes can't race on the same app.
concurrency:
  group: deploy-agent-teams
  cancel-in-progress: false

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      # JSON array of {name, tenant} to (re)deploy; "[]" when nothing changed.
      entries: ${{ steps.plan.outputs.entries }}
      # "true" only when a Fly token is configured — gates the deploy/orphan jobs.
      configured: ${{ steps.gate.outputs.configured }}
    steps:
      - uses: actions/checkout@v4

      - id: gate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ -n "${FLY_API_TOKEN:-}" ]; then
            echo "configured=true" >> "$GITHUB_OUTPUT"
          else
            echo "configured=false" >> "$GITHUB_OUTPUT"
            echo "::notice::secrets.FLY_API_TOKEN unset — fleet not wired, skipping."
          fi

      - id: plan
        env:
          ONLY: ${{ inputs.only }}
        run: |
          set -euo pipefail
          tenant_of() {  # tenant from deployments/<name>.yaml, else defaults, else prod
            sed -nE 's#^tenant:[[:space:]]*([^[:space:]#]+).*#\1#p' "$1" | head -n1
          }
          default_tenant="$(tenant_of deployments/defaults.yaml)"
          default_tenant="${default_tenant:-prod}"

          entries=()
          for f in deployments/*.yaml; do
            [ -e "$f" ] || continue
            b="$(basename "$f" .yaml)"
            [ "$b" = "defaults" ] && continue
            [ -n "${ONLY:-}" ] && [ "$b" != "$ONLY" ] && continue
            t="$(tenant_of "$f")"; t="${t:-$default_tenant}"
            entries+=("$(jq -cn --arg n "$b" --arg t "$t" '{name:$n, tenant:$t}')")
          done

          if [ "${#entries[@]}" -eq 0 ]; then
            echo "entries=[]" >> "$GITHUB_OUTPUT"
            echo "No active deployments to reconcile."
          else
            printf '%s\n' "${entries[@]}" | jq -cs 'sort_by(.name)' \
              | sed 's/^/entries=/' >> "$GITHUB_OUTPUT"
            echo "Deployments to reconcile: $(printf '%s\n' "${entries[@]}" | jq -r .name | paste -sd, -)"
          fi

  deploy:
    needs: plan
    if: ${{ needs.plan.outputs.configured == 'true' && needs.plan.outputs.entries != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJSON(needs.plan.outputs.entries) }}
    # Bind this cell to the deployment's TENANT Environment (one Environment per
    # tenant). The Environment holds this tenant's per-key secrets, `<TEAM>__<KEY>`.
    environment: ${{ matrix.entry.tenant }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install the bobi CLI from PyPI
        run: pip install "bobi==${BOBI_VERSION}"

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy ${{ matrix.entry.name }}
        env:
          # All secrets in scope (this tenant Environment + repo/org). `secrets`
          # has no dynamic key access, so we dump it as JSON and filter in the step.
          ALL_SECRETS: ${{ toJSON(secrets) }}
        run: |
          set -euo pipefail
          name="${{ matrix.entry.name }}"
          # Key prefix for this deployment's secrets: <TEAM>__, where TEAM is the
          # deployment name slug-normalized (lowercase+hyphen → upper+underscore).
          prefix="$(printf '%s' "$name" | tr 'a-z-' 'A-Z_')__"
          umask 077
          envfile="$RUNNER_TEMP/instance.env"
          # Materialize ONLY this deployment's per-key secrets: select keys with the
          # <TEAM>__ prefix and strip it. toJSON(secrets) also carries repo/org
          # secrets (FLY_API_TOKEN, GITHUB_TOKEN…); the prefix filter excludes them,
          # and the engine additionally drops anything not declared in the team's
          # agent.yaml.
          echo "$ALL_SECRETS" | jq -r --arg p "$prefix" \
            'to_entries[] | select(.key|startswith($p)) | "\(.key[($p|length):])=\(.value)"' \
            > "$envfile"
          # The whole reconcile (provision-or-update, live-secret presence check,
          # prune of undeclared keys, identity stamps) is the primitive's job.
          bobi deploy "$name" --env-file "$envfile"

  orphans:
    # Report Fly apps in the fleet that no longer have a deployments/ file, so a
    # human can `bobi destroy` them. Never auto-destroys (the volume is the
    # only copy of an instance's state). Enumerates the fleet inline (fly apps list
    # name-prefix filter, confirmed by the BOBI_FLEET stamp) — the framework's
    # scripts/fleet.sh isn't present in this repo.
    needs: plan
    if: ${{ needs.plan.outputs.configured == 'true' }}
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Surface unmanaged instances
        run: |
          set -euo pipefail
          fleet="$(sed -nE 's#^fleet:[[:space:]]*([^[:space:]#]+).*#\1#p' \
                     deployments/defaults.yaml | head -n1)"
          [ -n "$fleet" ] || { echo "No fleet in deployments/defaults.yaml — skip."; exit 0; }

          # Managed = the apps we have a deployments/<name>.yaml for. Honor a
          # per-deployment `fleet:` override so a different-fleet deployment (e.g.
          # a throwaway test) maps to the right app name.
          declare -A managed=()
          for f in deployments/*.yaml; do
            b="$(basename "$f" .yaml)"; [ "$b" = "defaults" ] && continue
            df="$(sed -nE 's#^fleet:[[:space:]]*([^[:space:]#]+).*#\1#p' "$f" | head -n1)"
            managed["${df:-$fleet}-$b"]=1
          done

          # Live members of THIS fleet: name-prefix candidates confirmed by stamp.
          orphans=()
          while IFS= read -r app; do
            [ -n "$app" ] || continue
            stamp="$(fly config show -a "$app" 2>/dev/null | jq -r '.env.BOBI_FLEET // empty')"
            [ "$stamp" = "$fleet" ] || continue
            [ -n "${managed[$app]:-}" ] || orphans+=("$app")
          done < <(fly apps list --json 2>/dev/null \
                     | jq -r --arg p "${fleet}-" '.[].Name | select(startswith($p))')

          if [ "${#orphans[@]}" -gt 0 ]; then
            echo "::warning::Unmanaged fleet instances (no deployments/ file): ${orphans[*]}"
            echo "Run \`bobi destroy <name>\` to remove each one (human-gated)."
          else
            echo "No unmanaged instances."
          fi
'''


@dataclass
class TeamSecrets:
    """A team's secret-wiring facts for the next-steps output."""
    team: str          # deployment name (== team package name)
    prefix: str        # GitHub secret-key prefix, e.g. "ENG_TEAM__"
    keys: list[str]    # declared secret keys (e.g. SLACK_BOT_TOKEN, ANTHROPIC_API_KEY)
    auth: str          # api_key | subscription


@dataclass
class ScaffoldResult:
    written: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)
    teams: list[TeamSecrets] = field(default_factory=list)
    fleet: str = ""
    tenant: str = ""
    version: str = ""
    repo_slug: str | None = None


def render_workflow(version: str) -> str:
    """The standalone deploy workflow YAML, pinned to `version`."""
    return WORKFLOW_TEMPLATE.replace("__BOBI_VERSION__", version)


def prefix_for(name: str) -> str:
    """GitHub secret-key prefix for a deployment — mirrors the workflow's
    `tr 'a-z-' 'A-Z_'` exactly (lowercase+hyphen → upper+underscore; other
    characters pass through unchanged)."""
    table = str.maketrans(
        "abcdefghijklmnopqrstuvwxyz-", "ABCDEFGHIJKLMNOPQRSTUVWXYZ_")
    return name.translate(table) + "__"


def discover_teams(project_path: Path) -> list[str]:
    """Team package names under `agents/` (dirs with an agent.yaml), sorted."""
    base = project_path / "agents"
    if not base.is_dir():
        return []
    return sorted(d.name for d in base.iterdir()
                  if (d / "agent.yaml").is_file())


def secret_keys_for(project_path: Path, team: str, auth: str) -> list[str]:
    """The per-key secrets a team needs in its tenant Environment.

    The team's declared `${VAR}` set (minus BOBI_* instance-identity vars
    the provisioner stamps from flags), plus the auth overlay: api_key mode needs
    ANTHROPIC_API_KEY; subscription mode must NOT have it (it would override the
    OAuth creds). Mirrors `deploy._secret_sets` so the wiring matches the engine.
    """
    from bobi.deploy import scan_declared_vars

    agent_yaml = project_path / "agents" / team / "agent.yaml"
    keys = [v for v in scan_declared_vars(agent_yaml)
            if not v.startswith("BOBI_")]
    if auth == "api_key":
        if "ANTHROPIC_API_KEY" not in keys:
            keys.append("ANTHROPIC_API_KEY")
    else:  # subscription: ANTHROPIC must be absent
        keys = [k for k in keys if k != "ANTHROPIC_API_KEY"]
    return keys


def detect_repo_slug(project_path: Path) -> str | None:
    """`owner/repo` from the git `origin` remote, or None — best-effort, for the
    copy-pasteable `gh … --repo` commands in the next-steps output."""
    try:
        out = subprocess.run(
            ["git", "-C", str(project_path), "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        return None
    url = out.stdout.strip()
    if not url:
        return None
    # git@github.com:owner/repo.git  |  https://github.com/owner/repo(.git)
    tail = url.split("github.com", 1)[-1].lstrip(":/")
    if tail.endswith(".git"):
        tail = tail[:-4]
    parts = tail.split("/")
    return f"{parts[0]}/{parts[1]}" if len(parts) >= 2 and parts[0] else None


def _render_defaults(fleet: str, tenant: str, event_server: str | None) -> str:
    es = (f"event_server: {event_server}\n" if event_server else
          "# event_server: https://<your-worker>.workers.dev   "
          "# omit to use the shared moda Worker\n")
    return (
        "# deployments/defaults.yaml — shared operator values applied under every\n"
        "# deployments/<name>.yaml. Precedence: built-ins < THIS < <name>.yaml < CLI.\n"
        "\n"
        "# Fleet namespace. App name = \"<fleet>-<name>\"; stamped BOBI_FLEET\n"
        "# (the membership key the deploy workflow enumerates by).\n"
        f"fleet: {fleet}\n"
        "\n"
        "# Tenant = the GitHub Environment holding this fleet's per-key secrets\n"
        "# (`<TEAM>__<KEY>`). One Environment per tenant.\n"
        f"tenant: {tenant}\n"
        "\n"
        f"{es}"
        "\n"
        "# Shared machine sizing — override per-instance for heavier teams.\n"
        "region: iad\n"
        "memory: 4gb\n"
        "cpus: 2\n"
        "volume_size: 15\n"
    )


def _render_deployment(team: str, auth: str) -> str:
    auth_line = "" if auth == "api_key" else f"auth: {auth}\n"
    return (
        f"# deployments/{team}.yaml — one instance (app <fleet>-{team}).\n"
        "# Adding/editing this file + a `deploy-*` tag is what deploys.\n"
        f"# Delivery: a LOCAL package (agents/{team}) -> ssh-push. Use `team-url:`\n"
        "# instead to pull a published tarball at first boot (no CI ssh needed).\n"
        f"team: {team}\n"
        f"{auth_line}"
        "# Secrets: per-key in the tenant Environment, keyed "
        f"{prefix_for(team)}<KEY>.\n"
        "secrets:\n"
        f"  env: {team}\n"
    )


def scaffold(project_path: Path, *, teams: list[str], fleet: str, tenant: str,
             event_server: str | None, auth: str, force: bool,
             version: str) -> ScaffoldResult:
    """Write the standalone CI workflow + deployments/ skeleton (non-destructive
    unless `force`), and gather each team's secret-wiring facts for next-steps."""
    result = ScaffoldResult(fleet=fleet, tenant=tenant, version=version,
                            repo_slug=detect_repo_slug(project_path))

    def write(rel: str, content: str) -> None:
        path = project_path / rel
        if path.exists() and not force:
            result.skipped.append(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        result.written.append(path)

    write(".github/workflows/deploy-agent-teams.yml", render_workflow(version))
    write("deployments/defaults.yaml",
          _render_defaults(fleet, tenant, event_server))
    for team in teams:
        write(f"deployments/{team}.yaml", _render_deployment(team, auth))
        result.teams.append(TeamSecrets(
            team=team, prefix=prefix_for(team),
            keys=secret_keys_for(project_path, team, auth), auth=auth))
    return result


def next_steps(result: ScaffoldResult) -> str:
    """The copy-pasteable `fly`/`gh` wiring commands, derived from the scaffold —
    Fly token → repo secret, then per-tenant Environment + each declared secret."""
    repo = result.repo_slug or "<owner>/<repo>"
    token_name = (result.repo_slug.split("/")[-1]
                  if result.repo_slug else "team-repo") + "-deploy"
    lines = [
        "Next steps — wire CI once:",
        "",
        "1. Fly deploy token → repo secret FLY_API_TOKEN:",
        f"     fly tokens create org -o <your-fly-org> --name {token_name} \\",
        f"       | gh secret set FLY_API_TOKEN --repo {repo}",
        "",
        f"2. GitHub Environment '{result.tenant}' + per-key secrets:",
        f"     gh api -X PUT repos/{repo}/environments/{result.tenant}",
    ]
    for ts in result.teams:
        keys = ", ".join(ts.keys) if ts.keys else "(none declared)"
        lines.append(f"     # {ts.team} (auth={ts.auth}) needs: {keys}")
        for k in ts.keys:
            lines.append(
                f"     gh secret set {ts.prefix}{k} "
                f"--env {result.tenant} --repo {repo}")
    lines += [
        "",
        f"3. Set `fleet:` (currently '{result.fleet}') + event_server in "
        "deployments/defaults.yaml, then ship:",
        "     git add -A && git commit -m 'ci: deploy automation' && git push",
        "     git tag deploy-1 && git push origin deploy-1",
    ]
    return "\n".join(lines)
