#!/usr/bin/env python3
"""Vendor Bobi's brand typefaces as local woff2 subsets.

bobi setup and the bobi web app are offline surfaces (DESIGN.md): no CDN, no
network at runtime. The design system under .claude/skills/bobi-design links
Geist / Geist Mono / Inter from Google Fonts; this script downloads the latin
and latin-ext subsets instead so the brand type survives with no outbound
request.

Google serves each family as a single variable woff2 per subset, so one file
covers every weight we use. Re-run only to refresh the vendored binaries:

    python3 scripts/fetch_brand_fonts.py bobi/webui_common/static/fonts
"""

from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# query name, CSS family name, file slug, weights we use
FAMILIES = [
    ("Geist", "Geist", "geist", (400, 700)),
    ("Geist+Mono", "Geist Mono", "geist-mono", (400, 600)),
    ("Inter", "Inter", "inter", (400, 600)),
]

WANT_SUBSETS = ("latin", "latin-ext")

BLOCK = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}", re.S
)


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> int:
    out_dir = pathlib.Path(sys.argv[1])
    out_dir.mkdir(parents=True, exist_ok=True)

    rules: list[str] = []
    total = 0

    for query, css_family, slug, (w_min, w_max) in FAMILIES:
        spec = f"{query}:wght@{w_min};{w_max}"
        css = get(
            f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
        ).decode("utf-8")

        # One variable file per subset covers the whole weight range, so keep
        # the first block per subset and drop the per-weight duplicates.
        seen: set[str] = set()
        for m in BLOCK.finditer(css):
            subset = m.group("subset")
            if subset not in WANT_SUBSETS or subset in seen:
                continue
            seen.add(subset)
            body = m.group("body")

            url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
            urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()

            name = f"{slug}-{subset}.woff2"
            data = get(url)
            (out_dir / name).write_bytes(data)
            total += len(data)
            print(f"  {name:28s} {len(data):>7,d} B")

            rules.append(
                "@font-face {\n"
                f'  font-family: "{css_family}";\n'
                "  font-style: normal;\n"
                f"  font-weight: {w_min} {w_max};\n"
                "  font-display: swap;\n"
                f'  src: url("fonts/{name}") format("woff2");\n'
                f"  unicode-range: {urange};\n"
                "}"
            )

    header = (
        "/* Bobi brand faces, self-hosted.\n"
        "   bobi setup and the bobi web app are offline surfaces (DESIGN.md): no\n"
        "   CDN, no network at runtime. The design system links these from Google\n"
        "   Fonts; we vendor the latin + latin-ext woff2 subsets instead so the\n"
        "   brand type survives with no outbound request.\n"
        "\n"
        "   Each file is a variable font spanning the declared weight range, so one\n"
        "   binary per family+subset covers every weight the UI uses.\n"
        "\n"
        "   Geist and Geist Mono: SIL OFL 1.1 (Vercel).\n"
        "   Inter: SIL OFL 1.1 (Rasmus Andersson). See fonts/LICENSE.md.\n"
        "\n"
        "   src paths are relative to this file so they keep resolving under a\n"
        "   mounted base path - static assets get no {{BASE}} substitution.\n"
        "\n"
        "   Generated by scripts/fetch_brand_fonts.py - do not hand-edit. */\n\n"
    )
    (out_dir.parent / "fonts.css").write_text(header + "\n\n".join(rules) + "\n")
    print(f"\n{len(rules)} faces, {total:,} B total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
